Repository SunriseCommunity/Sunrise, pull requests merged in 2024-12, with the labels that each got.

#30 Feat: Add "web/osu-getbeatmapinfo.php" endpoint.
  Server/Controllers/WebController.cs
  Server/Types/Enums/RequestType.cs
Labels: bug

#31 Password reset controller
  Server/API/Controllers/UserController.cs
  Server/API/Serializable/Request/ResetPassRequest.cs
  Server/Types/Enums/RequestType.cs
Labels: enhancement

#32 fix: Database update fix in user_file table
  Data/Migrations/000014_user_file_improvement.sql
  Server/Database/Models/UserFile.cs
  Server/Database/Services/User/Services/UserFileService.cs
Labels: bug, enhancement
